const names =  [
  ["", "Colorless"],
  ["B", "Mono-black"],
  ["W", "Mono-white"],
  ["U", "Mono-blue"],
  ["R", "Mono-red"],
  ["G", "Mono-green"],
  ["BW", "Orzhov"],
  ["BU", "Dimir"],
  ["BR", "Rakdos"],
  ["BG", "Golgari"],
  ["WU", "Azorius"],
  ["WR", "Boros"],
  ["WG", "Selesnya"],
  ["UR", "Izzet"],
  ["UG", "Simic"],
  ["RG", "Gruul"],
  ["BWU", "Esper"],
  ["BWR", "Mardu"],
  ["BWG", "Abzan"],
  ["WUG", "Bant"],
  ["BUR", "Grixis"],
  ["WUR", "Jeskai"],
  ["BGR", "Jund"],
  ["WGR", "Naya"],
  ["BGU", "Sultai"],
  ["RGU", "Temur"],
  ["WRGU", "Ink - Black-less"],
  ["BRGU", "Glint - White-less"],
  ["BWRG", "Dune - Blue-less"],
  ["BWUG", "Witch - Red-less"],
  ["BWUR", "Yore - Green-less"],
  ["BWURG", "5-colors"]
]

export {names};